name: aaa-project
dependencies:
  - jupyterlab
  - jupyter 
  - pip
  - pip:
    - joblib
    - click~=8.1.3 
    - numpy
    - pandas
    - lime~=0.2.0.1
    - shap~=0.40.0
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - imbalanced-learn==0.9.0 